sonar.exclusions=**/venv/**,**/.venv/**,**/site-packages/**,**/node_modules/**,**/target/**,**/dist/**,**/build/**
sonar.organization=TON_ORG
sonar.projectKey=TON_ORG_TON_PROJET
sonar.projectName=qa-plateforme-ui

sonar.sources=src/main/java
sonar.tests=src/test/java

sonar.java.binaries=target/classes
sonar.junit.reportPaths=target/surefire-reports
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml

sonar.sourceEncoding=UTF-8