const { chromium } = require('playwright');
(async () => {
  const browser = await chromium.launch();
  const context = await browser.newContext();
  const page = await context.newPage();
  const baseUrl = 'https://qacart-todo.herokuapp.com';
  await page.goto(`${baseUrl}/signup`, { waitUntil: 'networkidle' });
  const email = `user${Date.now()}@mail.com`;
  const firstName = 'TestFirst';
  const lastName = 'TestLast';
  const password = 'Password123!';
  const inputs = await page.$$('input');
  console.log('input count', inputs.length);
  await inputs[0].fill(firstName);
  await inputs[1].fill(lastName);
  await inputs[2].fill(email);
  await inputs[3].fill(password);
  await inputs[4].fill(password);
  const btn = await page.$('button[type=button]');
  if (!btn) throw new Error('Signup button not found');
  await btn.click();
  await page.waitForTimeout(5000);
  console.log('After signup URL', page.url());
  console.log('Title:', await page.title());
  const content = await page.content();
  console.log('CONTENT_START');
  console.log(content.slice(0,2000));
  console.log('CONTENT_END');
  await browser.close();
})();
