name: SonarCloud - UI PR

on:
  pull_request:
    branches: [ "main" ]
    paths:
      - "ui_selenium_bdd/**"

permissions:
  contents: read
  pull-requests: write

jobs:
  sonar-ui:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: maven

      - name: Build
        working-directory: ui_selenium_bdd
        run: mvn -B clean verify

      - name: Sonar Scan
        uses: SonarSource/sonarqube-scan-action@v2
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectBaseDir=ui_selenium_bdd
            -Dsonar.qualitygate.wait=true